openapi: 3.0.0
info: 
  version: 1.0.0
  title: Corporate Actions API V1
  description: Corporate Actions API V1
servers: 
  - url: <to be set>
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
  /corporateActions: 
   post: 
    operationId: createCorporateActions
    tags: 
     - corporateActions
    summary: Create Corporate Action
    description: Create Corporate Action
    responses: 
     '200': 
      description: Success
   get: 
    operationId: getCorporateActions
    tags: 
     - corporateActions
    summary: Get All Corporate Actions
    description: Get All Corporate Actions
    responses: 
     '200': 
      description: Success
  /corporateActions/{id}: 
   get: 
    operationId: getCorporateActionsById
    tags: 
     - corporateActions
    summary: Get Corporate Action By Id
    description: Get Corporate Action By Id
    responses: 
     '200': 
      description: Success
   delete: 
    operationId: deleteCorporateAction
    tags: 
     - corporateActions
    summary: Delete Corporate Action By Id
    description: Delete Corporate Action By Id
    responses: 
     '200': 
      description: Success
   put: 
    operationId: updateCorporateAction
    tags: 
     - corporateActions
    summary: Update Corporate Action By Id
    description: Update Corporate Action By Id
    responses: 
     '200': 
      description: Success
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
  schemas: 
   ErrorResponseList: 
    title : ErrorResponseList
    type: object
    properties: 
     Error: 
      type: object
      $ref: '#/components/schemas/Error'
   affectedSecurities: 
    title : affectedSecurities
    type: object
    properties: 
     symbol: 
      type: string
     name: 
      type: string
     id: 
      type: string
     actionDetails: 
      type: object
      $ref: '#/components/schemas/actionDetails'
     ISIN: 
      type: string
   EntityResponse: 
    title : EntityResponse
    type: object
    properties: 
     message: 
      type: string
     statusCode: 
      type: string
   Error: 
    title : Error
    type: object
    properties: 
     ErrorDescription: 
      type: string
     ErrorCode: 
      type: string
   actionDetails: 
    title : actionDetails
    type: object
    properties: 
     type: 
      type: string
     splitRatio: 
      type: string
   corporateActions: 
    title : corporateActions
    type: object
    properties: 
     exDate: 
      type: string
     affectedSecurities: 
      type: object
      $ref: '#/components/schemas/affectedSecurities'
     recordDate: 
      type: string
     id: 
      type: string
     type: 
      type: string
     paymentDate: 
      type: string
     issuer: 
      type: object
      $ref: '#/components/schemas/issuer'
   issuer: 
    title : issuer
    type: object
    properties: 
     name: 
      type: string
     tickerSymbol: 
      type: string
     id: 
      type: string
     ISIN: 
      type: string
