openapi: 3.0.0
info: 
  version: 1.0.0
  title: Benefits Base Plan Jobs API
  description: Benefits Base Plan Jobs API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /benefits/baseplan/jobs: 
   get: 
    operationId: GetBasePlanJobs
    tags: 
     - BaseplanJob
    summary: Get baseplan job
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/JobIDQueryParam'
     - $ref: '#/components/parameters/GroupIdQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
    responses: 
     '200': 
      description: Baseplan job retrieved succesfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/BaseplanJobListDTO'
  /benefits/baseplan/job: 
   post: 
    operationId: AddBasePlanJob
    tags: 
     - BaseplanJob
    summary: Add baselpan job
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BaseplanJobDTO'
    responses: 
     '200': 
      description: Baseplan job added succesfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
   put: 
    operationId: UpdateBasePlanJob
    tags: 
     - BaseplanJob
    summary: Update baseplan job
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BaseplanJobDTO'
    responses: 
     '200': 
      description: Baseplan job updated succesfully
      content: 
       application/json: 
        schema: 
         type: integer
  /benefits/baseplan/job/process: 
   post: 
    operationId: ProcessBasePlanJob
    tags: 
     - BaseplanJob
    summary: Process baseplan job
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/JobIdQueryParam'
     - $ref: '#/components/parameters/OverrideRetroEnrollmentEnforcementQueryParam'
     - $ref: '#/components/parameters/OverrideTierRestrictionsQueryParam'
     - $ref: '#/components/parameters/DebugFlagQueryParam'
    responses: 
     '200': 
      description: Baseplan job proccessed succesfully
      content: 
       application/json: 
        schema: 
         type: integer
components: 
  schemas: 
   BaseplanJobDTO: 
    title : BaseplanJobDTO
    type: object
    properties: 
     JobType: 
      type: string
      nullable: true
     GroupId: 
      type: integer
      nullable: true
     OriginalBasePlanId: 
      type: integer
      nullable: true
     JobId: 
      type: integer
      nullable: true
     JobName: 
      type: string
      nullable: true
     JobDescription: 
      type: string
      nullable: true
     OriginalEffectiveDate: 
      type: string
      nullable: true
     OriginalExpirationDate: 
      type: string
      nullable: true
     OriginalTerminationDate: 
      type: string
      nullable: true
     OriginalTerminationReason: 
      type: string
      nullable: true
     NewBasePlanId: 
      type: integer
      nullable: true
     NewEffectiveDate: 
      type: string
      nullable: true
     NewExpirationDate: 
      type: string
      nullable: true
     NewTierTypeId: 
      type: integer
      nullable: true
     NewTierTypeEffectiveDate: 
      type: string
      nullable: true
     NewLiabilityPackageId: 
      type: integer
      nullable: true
     ReOpenClaims: 
      type: string
      nullable: true
     ProcessingStatus: 
      type: string
      nullable: true
     GoToNextProcess: 
      type: string
      nullable: true
     Usage: 
      type: string
      nullable: true
   BaseplanJobListDTO: 
    title : BaseplanJobListDTO
    type: object
    properties: 
     JobId: 
      type: integer
     JobName: 
      type: string
     JobDescription: 
      type: string
      nullable: true
     JobType: 
      type: string
     JobTypeName: 
      type: string
      nullable: true
     ProcessingStatus: 
      type: string
     ProcessingStatusName: 
      type: string
      nullable: true
     GroupId: 
      type: integer
     GroupName: 
      type: string
      nullable: true
     GroupNumber: 
      type: string
      nullable: true
     DateCreated: 
      type: string
      format: date-time
     DateCompleted: 
      type: string
      format: date-time
      nullable: true
     TimeElapsed: 
      type: number
      nullable: true
     CreatedById: 
      type: integer
     CreatedBy: 
      type: string
      nullable: true
     OriginalBasePlanId: 
      type: integer
      nullable: true
     OriginalPlanName: 
      type: string
      nullable: true
     OriginalEffectiveDate: 
      type: string
      format: date-time
      nullable: true
     OriginalExpirationDate: 
      type: string
      format: date-time
      nullable: true
     OriginalTerminationDate: 
      type: string
      format: date-time
      nullable: true
     OriginalTerminationReason: 
      type: string
      nullable: true
     OriginalTerminationReasonName: 
      type: string
      nullable: true
     OriginalRealPlanId: 
      type: integer
      nullable: true
     OriginalPlanCoverageEffDate: 
      type: string
      format: date-time
      nullable: true
     OriginalPlanCoverageExpDate: 
      type: string
      format: date-time
      nullable: true
     OriginalPlanTotalMembers: 
      type: integer
      nullable: true
     NewBasePlanId: 
      type: integer
      nullable: true
     NewPlanName: 
      type: string
      nullable: true
     NewEffectiveDate: 
      type: string
      format: date-time
      nullable: true
     NewExpirationDate: 
      type: string
      format: date-time
      nullable: true
     NewTierTypeId: 
      type: integer
      nullable: true
     NewTierTypeEffectiveDate: 
      type: string
      format: date-time
      nullable: true
     NewLiabilityPackageId: 
      type: integer
      nullable: true
     ReOpenClaims: 
      type: string
      nullable: true
     NewTierTypeName: 
      type: string
      nullable: true
     NewLiabilityPackageName: 
      type: string
      nullable: true
     RetroClaimActivityCode: 
      type: string
      nullable: true
     RetroClaimActivity: 
      type: string
      nullable: true
     UseStandardTimeSlicesCode: 
      type: string
      nullable: true
     UseStandardTimeSlices: 
      type: string
      nullable: true
     NumberOfAttempts: 
      type: integer
      nullable: true
     TotalMembership: 
      type: integer
      nullable: true
     NumberSucceeded: 
      type: integer
      nullable: true
     PercentSucceeded: 
      type: string
      nullable: true
     NumErrors: 
      type: string
      nullable: true
     PercentErrors: 
      type: string
      nullable: true
     NumAborted: 
      type: integer
      nullable: true
     PercentAborted: 
      type: string
      nullable: true
     IsAbortable: 
      type: string
      nullable: true
     IsContinuable: 
      type: string
      nullable: true
     LastUpdatedById: 
      type: integer
     LastUpdatedBy: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
     Notes: 
      type: string
      nullable: true
  parameters: 
   JobIDQueryParam: 
    in: query
    name: JobID
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   GroupIdQueryParam: 
    in: query
    name: GroupId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   UsageQueryParam: 
    in: query
    name: Usage
    required: false
    schema: 
     type: string
    description: description of parameter passed
   JobIdQueryParam: 
    in: query
    name: JobId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   OverrideRetroEnrollmentEnforcementQueryParam: 
    in: query
    name: OverrideRetroEnrollmentEnforcement
    required: false
    schema: 
     type: string
    description: description of parameter passed
   OverrideTierRestrictionsQueryParam: 
    in: query
    name: OverrideTierRestrictions
    required: false
    schema: 
     type: string
    description: description of parameter passed
   DebugFlagQueryParam: 
    in: query
    name: DebugFlag
    required: false
    schema: 
     type: integer
    description: description of parameter passed
