openapi: 3.0.0
info: 
  version: 1.0.0
  title: Brokers
  description: Brokers API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /benefit/baseplan/rule: 
   post: 
    operationId: GetBasePlanAgeRules
    tags: 
     - BasePlanAgeRule
    summary: Get Base Plan Age Rule
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BasePlanAgeRuleSearchDTO'
    responses: 
     '200': 
      description: BasePlanAgeRules Retrieved succesfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/BasePlanAgeRuleListDTO'
   put: 
    operationId: UpdateBasePlanAgeRule
    tags: 
     - BasePlanAgeRule
    summary: Update Base Plan Age Rule
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BasePlanAgeRuleDTO'
    responses: 
     '200': 
      description: BasePlanAgeRules Updated succesfully
      content: 
       application/json: 
        schema: 
         type: integer
   delete: 
    operationId: DeleteBasePlanAgeRule
    tags: 
     - BasePlanAgeRule
    summary: Delete Base Plan Age Rule
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/BasePlanAgeRuleIdQueryParam'
    responses: 
     '200': 
      description: BasePlanAgeRules Deleted succesfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
components: 
  schemas: 
   BasePlanAgeRuleDTO: 
    title : BasePlanAgeRuleDTO
    type: object
    properties: 
     PlanID: 
      type: integer
      nullable: true
     PlanAgeExceptionType: 
      type: string
      nullable: true
     AgeType: 
      type: string
      nullable: true
     MinimumAge: 
      type: integer
      nullable: true
     MaximumAge: 
      type: integer
      nullable: true
     AttachmentCategoryId: 
      type: integer
      nullable: true
     Self: 
      type: string
      default: "Y"
      nullable: true
     Spouse: 
      type: string
      default: "Y"
      nullable: true
     Child: 
      type: string
      default: "Y"
      nullable: true
     Other: 
      type: string
      default: "Y"
      nullable: true
     ExplanationId: 
      type: integer
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
      default: "01/01/1900"
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      default: "12/31/9999"
      nullable: true
     BasePlanAgeRuleId: 
      type: integer
      nullable: true
   BasePlanAgeRuleSearchDTO: 
    title : BasePlanAgeRuleSearchDTO
    type: object
    properties: 
     Usage: 
      type: string
      default: "|INIT|"
      nullable: true
     PlanId: 
      type: integer
      nullable: true
   BasePlanAgeRuleListDTO: 
    title : BasePlanAgeRuleListDTO
    type: object
    properties: 
     BasePlanAgeRuleId: 
      type: integer
      description: 
     PlanID: 
      type: integer
     PlanAgeExceptionType: 
      type: string
     PlanAgeExceptionName: 
      type: string
      nullable: true
     AgeType: 
      type: string
     MinimumAge: 
      type: integer
      nullable: true
     MaximumAge: 
      type: integer
      nullable: true
     AttachmentCategoryId: 
      type: integer
      nullable: true
     AttachmentCategoryName: 
      type: string
      nullable: true
     Self: 
      type: string
      nullable: true
     Spouse: 
      type: string
      nullable: true
     Child: 
      type: string
      nullable: true
     Other: 
      type: string
      nullable: true
     ExplanationId: 
      type: integer
      nullable: true
     ExplanationAbbreviation: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
     ExpirationDate: 
      type: string
     LastUpdatedAt: 
      type: string
      nullable: true
     LastUpdatedBy: 
      type: string
      nullable: true
  parameters: 
   BasePlanAgeRuleIdQueryParam: 
    in: query
    name: BasePlanAgeRuleId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
