openapi: 3.0.0
info: 
  version: 1.0.0
  title: Benefit API
  description: Benefit API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /benefit/benefitcoverages/get: 
   post: 
    operationId: GetBenefitCoverages
    tags: 
     - Benefit
    summary: Get benefit coverages
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BenefitCoverageSearchDTO'
    responses: 
     '200': 
      description: Benefit coverages retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/BenefitCoverageListDTO'
  /benefit/benefitcoverage: 
   post: 
    operationId: AddBenefitCoverage
    tags: 
     - Benefit
    summary: Add benefit coverage
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BenefitCoverageDTO'
    responses: 
     '200': 
      description: Benefit coverages added successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
   put: 
    operationId: UpdateBenefitCoverage
    tags: 
     - Benefit
    summary: Update benefit coverage
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BenefitCoverageDTO'
    responses: 
     '200': 
      description: Benefit coverages updated successfully
      content: 
       application/json: 
        schema: 
         type: integer
  /benefit/toplevelsummaryofbenefitmap: 
   post: 
    operationId: GetTopLevelSummaryOfBenefitMap
    tags: 
     - Benefit
    summary: Get top level summary of benefit map
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/TopLevelSummaryOfBenefitMapSearchDTO'
    responses: 
     '200': 
      description: top level summary of benefit map  retrieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/TopLevelSummaryOfBenefitMapListDTO'
  /benefit/benefitcategories/get: 
   post: 
    operationId: GetBenefitCategories
    tags: 
     - Benefit
    summary: Get benefit categories
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/BnfCategorySearchDTO'
    responses: 
     '200': 
      description: Benefit categroies retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/BnfCategoryListDTO'
  /benefit/baseplanjobs: 
   get: 
    operationId: GetBasePlanJobs
    tags: 
     - Benefit
    summary: Get base plan jobs
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/JobIDQueryParam'
     - $ref: '#/components/parameters/GroupIdQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
    responses: 
     '200': 
      description: Success
   post: 
    operationId: AddBasePlanJobs
    tags: 
     - Benefit
    summary: Add base plan job 
    description: Description of path
    responses: 
     '200': 
      description: Success
   put: 
    operationId: UpdateBasePlanJobs
    tags: 
     - Benefit
    summary: Update base plan job 
    description: Description of path
    responses: 
     '200': 
      description: Success
components: 
  schemas: 
   BenefitCoverageSearchDTO: 
    title : BenefitCoverageSearchDTO
    type: object
    properties: 
     Usage: 
      type: string
      default: "|USAGE1|"
      nullable: true
     EntityId: 
      type: integer
      nullable: true
     EntityType: 
      type: string
      nullable: true
     CoverageEntityId: 
      type: integer
      nullable: true
     CoverageEntityType: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      nullable: true
     BenefitCoverageId: 
      type: integer
      nullable: true
     BasePlanId: 
      type: integer
      nullable: true
     Level: 
      type: string
      default: ALL
      nullable: true
     ReturnRidersAndQualifiers: 
      type: string
      default: Y
      nullable: true
   BenefitCoverageListDTO: 
    title : BenefitCoverageListDTO
    type: object
    properties: 
     BenefitCoverageId: 
      type: integer
      description: 
     EntityId: 
      type: integer
     EntityTypeId: 
      type: integer
     CoverageEntityId: 
      type: integer
     CoverageEntityType: 
      type: string
     CoverageType: 
      type: string
      nullable: true
     Name: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
     ExpirationDate: 
      type: string
      format: date-time
     TerminationReason: 
      type: string
      nullable: true
     TerminationReasonName: 
      type: string
      nullable: true
     TierItemId: 
      type: integer
      nullable: true
     TierName: 
      type: string
      nullable: true
     TierCode: 
      type: string
      nullable: true
     TierAsOfDate: 
      type: string
      format: date-time
      nullable: true
     OverrideRetroEnrollmentEnforcement: 
      type: string
      nullable: true
     OverrideTierRestrictions: 
      type: string
     AppliedLevel: 
      type: string
      nullable: true
     AppliedLevelName: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
     LastUpdatedBy: 
      type: integer
     LastUpdatedByName: 
      type: string
      nullable: true
     SortKey: 
      type: integer
      nullable: true
   BenefitCoverageDTO: 
    title : BenefitCoverageDTO
    type: object
    properties: 
     BenefitCoverageId: 
      type: integer
      nullable: true
     GroupID: 
      type: integer
      nullable: true
     EntityID: 
      type: integer
      nullable: true
     EntityType: 
      type: string
      nullable: true
     CoverageEntityId: 
      type: integer
      nullable: true
     CoverageEntityType: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
      nullable: true
     ExpirationDate: 
      type: string
      nullable: true
     TerminationReason: 
      type: string
      nullable: true
     TierItemId: 
      type: integer
      nullable: true
     TierAsOfDate: 
      type: string
      nullable: true
     OverrideRetroEnrollmentEnforcement: 
      type: string
      nullable: true
     OverrideTierRestrictions: 
      type: string
      nullable: true
     ProcedureCaller: 
      type: string
      nullable: true
   TopLevelSummaryOfBenefitMapSearchDTO: 
    title : TopLevelSummaryOfBenefitMapSearchDTO
    type: object
    properties: 
     Usage: 
      type: string
      default: "|NORMAL|"
      nullable: true
     MemberCoverageId: 
      type: integer
      nullable: true
     GroupId: 
      type: integer
      nullable: true
     LiabilityPackageId: 
      type: integer
      nullable: true
     PlanId: 
      type: integer
      nullable: true
     ServiceDateFrom: 
      type: string
      format: date-time
      nullable: true
   TopLevelSummaryOfBenefitMapListDTO: 
    title : TopLevelSummaryOfBenefitMapListDTO
    type: object
    properties: 
     SOBReportPath: 
      type: string
      nullable: true
     SOBReportPathId: 
      type: integer
      nullable: true
     SOBReportPathCrystal: 
      type: string
      nullable: true
     EntityId: 
      type: integer
      nullable: true
     EntityType: 
      type: string
      nullable: true
     PlanName: 
      type: string
      nullable: true
   BnfCategorySearchDTO: 
    title : BnfCategorySearchDTO
    type: object
    properties: 
     BnfCategoryID: 
      type: integer
      nullable: true
     ParentId: 
      type: integer
      nullable: true
     PlanId: 
      type: integer
      nullable: true
     Usage: 
      type: string
      nullable: true
     Flag: 
      type: integer
      nullable: true
     GroupID: 
      type: integer
      nullable: true
     BnfCategoryName: 
      type: string
      nullable: true
     MemberCoverageID: 
      type: integer
      nullable: true
     ResultCount: 
      type: integer
      nullable: true
     ServiceDateFrom: 
      type: string
      nullable: true
     LiabilityPackageItemLevelMapId: 
      type: integer
      nullable: true
   BnfCategoryListDTO: 
    title : BnfCategoryListDTO
    type: object
    properties: 
     BnfCategoryID: 
      type: integer
     BnfCategoryType: 
      type: string
     BnfCategoryLevel: 
      type: integer
     ParentID: 
      type: integer
      nullable: true
     ParentName: 
      type: string
      nullable: true
     PlanID: 
      type: integer
      nullable: true
     BnfCategoryName: 
      type: string
     RateType: 
      type: string
      nullable: true
     Self: 
      type: string
     Spouse: 
      type: string
     Child: 
      type: string
     Other: 
      type: string
     EffectiveDate: 
      type: string
      format: date-time
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      nullable: true
     AgeType: 
      type: string
      nullable: true
     AgeRangeBegin: 
      type: integer
      nullable: true
     AgeRangeEnd: 
      type: integer
      nullable: true
     ContinuousCoveragePeriod: 
      type: integer
      nullable: true
     MinimumCoveragePeriod: 
      type: integer
      nullable: true
     SummaryOfBenefitsDisplayStatus: 
      type: string
      nullable: true
     GraduatingBenefits: 
      type: string
      nullable: true
     Description: 
      type: string
      nullable: true
     ChildType: 
      type: string
      nullable: true
     RateUnitType: 
      type: string
      nullable: true
     RateUnitValue: 
      type: string
      nullable: true
     BnfCategoryNameWithRate: 
      type: string
      nullable: true
     ExpenseAccountType: 
      type: string
      nullable: true
     ExpenseAccountSubType: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
     LastUpdatedBy: 
      type: string
     BnfCategoryWithLiability: 
      type: string
      nullable: true
     LiabilityEffectiveDate: 
      type: string
      format: date-time
      nullable: true
     LiabilityExpirationDate: 
      type: string
      format: date-time
      nullable: true
     LiabilityMapped: 
      type: string
      nullable: true
     AppliedLevel: 
      type: string
      nullable: true
     AppliedLevelName: 
      type: string
      nullable: true
     IncludeInReinsurance: 
      type: string
      nullable: true
     IncludeInReinsuranceName: 
      type: string
      nullable: true
     SortKey: 
      type: number
      nullable: true
     PlanName: 
      type: string
      nullable: true
     MemberCoverageID: 
      type: integer
      nullable: true
     ServiceDateFrom: 
      type: string
      format: date-time
      nullable: true
     ServiceTypeCode: 
      type: string
      nullable: true
     Class: 
      type: string
      nullable: true
     SubClass: 
      type: string
      nullable: true
     BenefitsReportClass: 
      type: string
      nullable: true
     BenefitsReportSubClass: 
      type: string
      nullable: true
     COBConsideration: 
      type: string
   BasePlanJobListDTO: 
    title : BasePlanJobListDTO
    type: object
    properties: 
     JobId: 
      type: integer
      nullable: true
     JobName: 
      type: string
      nullable: true
     JobDescription: 
      type: string
      nullable: true
     JobType: 
      type: string
      nullable: true
     JobTypeName: 
      type: string
      nullable: true
     ProcessingStatus: 
      type: string
      nullable: true
     ProcessingStatusName: 
      type: string
      nullable: true
     GroupId: 
      type: integer
      nullable: true
     GroupName: 
      type: string
      nullable: true
     GroupNumber: 
      type: string
      nullable: true
     DateCreated: 
      type: string
      nullable: true
     DateCompleted: 
      type: string
      nullable: true
     TimeElapsed: 
      type: number
      nullable: true
     CreatedById: 
      type: integer
      nullable: true
     CreatedBy: 
      type: string
      nullable: true
     OriginalBasePlanId: 
      type: integer
      nullable: true
     OriginalPlanName: 
      type: string
      nullable: true
     OriginalEffectiveDate: 
      type: string
      nullable: true
     OriginalExpirationDate: 
      type: string
      nullable: true
     OriginalTerminationDate: 
      type: string
      nullable: true
     OriginalTerminationReason: 
      type: string
      nullable: true
     OriginalTerminationReasonName: 
      type: string
      nullable: true
     OriginalRealPlanId: 
      type: integer
      nullable: true
     OriginalPlanCoverageEffDate: 
      type: string
      nullable: true
     OriginalPlanCoverageExpDate: 
      type: string
      nullable: true
     OriginalPlanTotalMembers: 
      type: integer
      nullable: true
     NewBasePlanId: 
      type: integer
      nullable: true
     NewPlanName: 
      type: string
      nullable: true
     NewEffectiveDate: 
      type: string
      nullable: true
     NewExpirationDate: 
      type: string
      nullable: true
     NewTierTypeId: 
      type: integer
      nullable: true
     NewTierTypeEffectiveDate: 
      type: string
      nullable: true
     NewLiabilityPackageId: 
      type: integer
      nullable: true
     ReOpenClaims: 
      type: string
      nullable: true
     NewTierTypeName: 
      type: string
      nullable: true
     NewLiabilityPackageName: 
      type: string
      nullable: true
     RetroClaimActivityCode: 
      type: string
      nullable: true
     RetroClaimActivity: 
      type: string
      nullable: true
     UseStandardTimeSlicesCode: 
      type: string
      nullable: true
     UseStandardTimeSlices: 
      type: string
      nullable: true
     NumberOfAttempts: 
      type: integer
      nullable: true
     TotalMembership: 
      type: integer
      nullable: true
     NumberSucceeded: 
      type: integer
      nullable: true
     PercentSucceeded: 
      type: string
      nullable: true
     NumErrors: 
      type: integer
      nullable: true
     PercentErrors: 
      type: string
      nullable: true
     NumAborted: 
      type: integer
      nullable: true
     PercentAborted: 
      type: string
      nullable: true
     IsAbortable: 
      type: string
      nullable: true
     IsContinuable: 
      type: string
      nullable: true
     LastUpdatedById: 
      type: integer
      nullable: true
     LastUpdatedBy: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      nullable: true
     Notes: 
      type: string
      nullable: true
  parameters: 
   JobIDQueryParam: 
    in: query
    name: JobID
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   GroupIdQueryParam: 
    in: query
    name: GroupId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   UsageQueryParam: 
    in: query
    name: Usage
    required: false
    schema: 
     type: string
    description: description of parameter passed
