openapi: 3.0.0
info: 
  version: 1.0.0
  title: Capitation Rate Entity Map API
  description: Capitation Rate Entity Map API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /finance/capitation/rateentitymap: 
   get: 
    operationId: GetCapitationRateEntityMap
    tags: 
     - Capitation Rate Entity Map
    summary: Get Capitation Rate Entity Map
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/CapitationRateIdQueryParam'
     - $ref: '#/components/parameters/Usage QueryParam'
    responses: 
     '200': 
      description: Capitation Rate Entity Map retieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/CapitationRateEntityMapListDTO'
   post: 
    operationId: AddCapitationRateEntityMap
    tags: 
     - Capitation Rate Entity Map
    summary: Add Capitation Rate Entity Map
    description: Description of path
    responses: 
     '200': 
      description: Capitation Rate Entity Map added successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
   put: 
    operationId: UpdateCapitationRateEntityMap
    tags: 
     - Capitation Rate Entity Map
    summary: Update Capitation Rate Entity Map
    description: Description of path
    responses: 
     '200': 
      description: Capitation Rate Entity Map updated successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /finance/capitation/removerateentitymap: 
   post: 
    operationId: DeleteCapitationRateEntityMap
    tags: 
     - Capitation Rate Entity Map
    summary: Delete Capitation Rate Entity Map
    description: Description of path
    responses: 
     '200': 
      description: Capitation Rate Entity Map deleted successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /finance/capitation/rateentitymaphistory: 
   post: 
    operationId: GetCapitationRateEntityMapHistory
    tags: 
     - Capitation Rate Entity Map
    summary: Capitation Rate Entity Map History
    description: Description of path
    responses: 
     '200': 
      description: Capitation Rate Entity Map History retieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/CapitationRateEntityMapHistoryListDTO'
components: 
  schemas: 
   CapitationRateEntityMapListDTO: 
    title : CapitationRateEntityMapListDTO
    type: object
    properties: 
     CapitationRateEntityId: 
      type: integer
      description: 
     CapitationRateId: 
      type: integer
      description: 
     CapitationRateName: 
      type: string
      nullable: true
     CapitationRateDescription: 
      type: string
      nullable: true
     Action: 
      type: string
     ActionName: 
      type: string
      nullable: true
     EntityType: 
      type: string
     EntityTypeName : 
      type: string
      nullable: true
     EntityIdentifier: 
      type: string
      nullable: true
     EntityId: 
      type: integer
      nullable: true
     EntityIdentifier2: 
      type: string
      nullable: true
     EntityId2: 
      type: integer
      nullable: true
     RangeBegin: 
      type: integer
      nullable: true
     RangeEnd: 
      type: integer
      nullable: true
     QualifierType: 
      type: string
      nullable: true
     QualifierPlanName: 
      type: string
      nullable: true
     AidCodeCategoryCode: 
      type: string
      nullable: true
     AidCodeCategory: 
      type: string
      nullable: true
     AidCodeSubCategoryCode: 
      type: string
      nullable: true
     AidCodeSubCategory: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
      format: date
      nullable: true
     ExpirationDate: 
      type: string
      format: date
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date
      nullable: true
     LastUpdatedById: 
      type: integer
      nullable: true
     LastUpdatedBy: 
      type: string
      nullable: true
   CapitationRateEntityMapDTO: 
    title : CapitationRateEntityMapDTO
    type: object
    properties: 
     CapitationRateId: 
      type: integer
      nullable: true
     CapitationRateEntityId: 
      type: integer
      nullable: true
     Action: 
      type: string
      nullable: true
     EntityType: 
      type: string
      nullable: true
     EntityId: 
      type: integer
      nullable: true
     EntityId2: 
      type: integer
      nullable: true
     RangeBegin: 
      type: integer
      nullable: true
     RangeEnd: 
      type: integer
      nullable: true
     EffectiveDate: 
      type: string
      format: date
      nullable: true
     ExpirationDate: 
      type: string
      format: date
      nullable: true
     DebugFlag: 
      type: integer
      nullable: true
     SPName: 
      type: string
      nullable: true
   CapitationRateEntityMapHistorySearchDTO: 
    title : CapitationRateEntityMapHistorySearchDTO
    type: object
    properties: 
     CapitationRateEntityId: 
      type: integer
      nullable: true
     CapitationRateId: 
      type: integer
      nullable: true
     Usage: 
      type: string
      nullable: true
     DebugFlag: 
      type: integer
      nullable: true
     SPName: 
      type: string
      nullable: true
   CapitationRateEntityMapHistoryListDTO: 
    title : CapitationRateEntityMapHistoryListDTO
    type: object
    properties: 
     HistoryId: 
      type: integer
      description: 
     CapitationRateEntityId: 
      type: integer
      description: 
     ChangedById: 
      type: integer
      nullable: true
     ChangedByName: 
      type: string
      nullable: true
     ChangedAt: 
      type: string
      format: date-time
      nullable: true
     ChangeType: 
      type: string
     ChangeTypeName: 
      type: string
      nullable: true
     Action: 
      type: string
     ActionName: 
      type: string
      nullable: true
     EntityType: 
      type: string
     EntityTypeName: 
      type: string
      nullable: true
     EntityIdentifier: 
      type: string
      nullable: true
     EntityId: 
      type: integer
      nullable: true
     EntityIdentifier2: 
      type: string
      nullable: true
     EntityId2: 
      type: integer
      nullable: true
     RangeBegin: 
      type: integer
      nullable: true
     RangeEnd: 
      type: integer
      nullable: true
     QualifierType: 
      type: string
      nullable: true
     QualifierPlanName: 
      type: string
      nullable: true
     AidCodeCategoryCode: 
      type: string
      nullable: true
     AidCodeCategory: 
      type: string
      nullable: true
     AidCodeSubCategoryCode: 
      type: string
      nullable: true
     AidCodeSubCategory: 
      type: string
      nullable: true
     EffectiveDate: 
      type: string
      format: date
      nullable: true
     ExpirationDate: 
      type: string
      format: date
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
      nullable: true
     LastUpdatedById: 
      type: integer
      description: 
     LastUpdatedBy: 
      type: string
      nullable: true
  parameters: 
   CapitationRateIdQueryParam: 
    in: query
    name: CapitationRateId
    required: true
    schema: 
     type: integer
    description: description of parameter passed
   Usage QueryParam: 
    in: query
    name: Usage 
    required: true
    schema: 
     type: string
     default: "|INIT|"
    description: description of parameter passed
