openapi: 3.0.0
info: 
  version: 1.0.0
  title: Claim Billing
  description: Claim Billing
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /claim/dental/documentrequestrecords: 
   get: 
    operationId: GetDocumentRequestRecords
    tags: 
     - Claim Billing
    summary: Get Document Requests Records
    description: Description of path
    responses: 
     '200': 
      description: Document Request Records Retreived Successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/DocumentRequestsRecordListDTO'
  /claim/dental/post: 
   post: 
    operationId: PostClaim
    tags: 
     - Claim Billing
    summary: Post Claim
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/PostClaimDTO'
    responses: 
     '200': 
      description: Post Claim Successfull
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /claim/dental/postingrecord: 
   put: 
    operationId: UpdatePostingRecord
    tags: 
     - Claim Billing
    summary: Update Posting Record
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/UpdatePostingRecordDTO'
    responses: 
     '200': 
      description: Posting Record Updated Successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /claim/dental/postingrecords: 
   get: 
    operationId: GetClaimBillingRecords
    tags: 
     - Claim Billing
    summary: Get Claim Billing Records
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/ClaimIdQueryParam'
     - $ref: '#/components/parameters/ClaimBillingRecordIdQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
    responses: 
     '200': 
      description: Claim Billing Records Retreived Successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/ClaimBillingRecordListDTO'
  /claim/dental/billrecords: 
   get: 
    operationId: GetBillRecordsForClaims
    tags: 
     - Claim Billing
    summary: Get Bill Records For Claims
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/ClaimIdQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
     - $ref: '#/components/parameters/DebugFlagQueryParam'
    responses: 
     '200': 
      description: Bill Records For Claims Retreived Successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/BillRecordsForClaimListDTO'
components: 
  schemas: 
   DocumentRequestsRecordSearchDTO: 
    title : DocumentRequestsRecordSearchDTO
    type: object
    properties: 
     JobId: 
      type: integer
      nullable: true
     RecordStatus: 
      type: string
      nullable: true
     RecordType: 
      type: string
      nullable: true
     ClaimId: 
      type: integer
      nullable: true
     MemberId: 
      type: integer
      nullable: true
     EntityType: 
      type: string
      nullable: true
     EntityID: 
      type: integer
      nullable: true
     ReferringEntity: 
      type: string
      nullable: true
     Step: 
      type: string
      nullable: true
     FulfilledByJobId: 
      type: integer
      nullable: true
     ReturnLatest: 
      type: string
      nullable: true
     Usage: 
      type: string
      nullable: true
     DebugFlag: 
      type: integer
      nullable: true
   DocumentRequestsRecordListDTO: 
    title : DocumentRequestsRecordListDTO
    type: object
    properties: 
     RecordId: 
      type: integer
      nullable: true
     RecordType: 
      type: string
      nullable: true
     RecordTypeName: 
      type: string
      nullable: true
     CreationDate: 
      type: string
      format: date-time
      nullable: true
     RecordStatus: 
      type: string
      nullable: true
     RecordStatusName: 
      type: string
      nullable: true
     EntityType: 
      type: string
      nullable: true
     EntityTypeName: 
      type: string
      nullable: true
     DocumentType: 
      type: string
      nullable: true
     DocumentTypeName: 
      type: string
      nullable: true
     MemberId: 
      type: integer
      nullable: true
     SubscriberContractId: 
      type: integer
      nullable: true
     MemberCoverageId: 
      type: integer
      nullable: true
     MemberLastName: 
      type: string
      nullable: true
     MemberFirstName: 
      type: string
      nullable: true
     MemberNumber: 
      type: string
      nullable: true
     GroupId: 
      type: integer
      nullable: true
     GroupNumber: 
      type: string
      nullable: true
     GroupName: 
      type: string
      nullable: true
     ProviderId: 
      type: integer
      nullable: true
     OfficeId: 
      type: integer
      nullable: true
     ReferringProviderId: 
      type: integer
      nullable: true
     ReferringOfficeId: 
      type: integer
      nullable: true
     ReportId: 
      type: integer
      nullable: true
     ReportName: 
      type: string
      nullable: true
     ReportPath: 
      type: string
      nullable: true
     NumberOfClaims: 
      type: integer
      nullable: true
     JobId: 
      type: integer
      nullable: true
     JobNumber: 
      type: string
      nullable: true
     JobStatus: 
      type: string
      nullable: true
     JobStatusName: 
      type: string
      nullable: true
     JobDetailId: 
      type: integer
      nullable: true
     DocumentID: 
      type: integer
      nullable: true
     DocumentNumber: 
      type: string
      nullable: true
     Location: 
      type: string
      nullable: true
     FilePath: 
      type: string
      nullable: true
     FulfillmentMethod: 
      type: string
      nullable: true
     FulfillmentMethodName: 
      type: string
      nullable: true
     JobFulfillmentMethodCode: 
      type: string
      nullable: true
     JobFulfillmentMethod: 
      type: string
      nullable: true
     FulfillmentID: 
      type: string
      nullable: true
     Fax: 
      type: string
      nullable: true
     Email: 
      type: string
      nullable: true
     FulfillmentStatus: 
      type: string
      nullable: true
     FulfillmentStatusName: 
      type: string
      nullable: true
     FulfilledAt: 
      type: string
      format: date-time
      nullable: true
     FulfilledBy: 
      type: integer
      nullable: true
     FulfilledByName: 
      type: string
      nullable: true
     SuppressionReason: 
      type: string
      nullable: true
     SuppressionReasonName: 
      type: string
      nullable: true
     ClaimId: 
      type: integer
      nullable: true
     ClaimNumber: 
      type: string
      nullable: true
     AdjustmentVersion: 
      type: integer
      nullable: true
     VendorName: 
      type: string
      nullable: true
     VendorInfo: 
      type: string
      nullable: true
     ClaimRedirectAddressId: 
      type: integer
      nullable: true
     ClaimRedirectAddressName: 
      type: string
      nullable: true
     Message: 
      type: string
     MemberEOBPreference: 
      type: string
      nullable: true
     EmailNotification: 
      type: string
      nullable: true
     CollateImages: 
      type: string
      nullable: true
     CoversheetGroupingCode: 
      type: string
      nullable: true
     CoversheetGrouping: 
      type: string
      nullable: true
     DocumentRequestId: 
      type: integer
      nullable: true
   ClaimBillingRecordListDTO: 
    title : ClaimBillingRecordListDTO
    type: object
    properties: 
     ClaimBillingRecordId: 
      type: integer
      nullable: true
     ClaimId: 
      type: integer
      nullable: true
     ClaimNumber: 
      type: string
      nullable: true
     BillingEntityId: 
      type: integer
      nullable: true
     AdjustmentVersion: 
      type: integer
      nullable: true
     BillingEntityMapId: 
      type: integer
      nullable: true
     BillingEntityNumber: 
      type: string
      nullable: true
     BillingEntityName: 
      type: string
      nullable: true
     RecordTypeCode: 
      type: string
      nullable: true
     RecordType: 
      type: string
      nullable: true
     RecordStatusCode: 
      type: string
      nullable: true
     RecordStatus: 
      type: string
      nullable: true
     Amount: 
      type: number
      nullable: true
     CreationDate: 
      type: string
      format: date-time
      nullable: true
     ProcessedDate: 
      type: string
      format: date-time
      nullable: true
     ParentAccountID: 
      type: integer
      nullable: true
     ParentAccountNumber: 
      type: string
      nullable: true
     ParentAccountName: 
      type: string
      nullable: true
     CompanyID: 
      type: integer
      nullable: true
     CompanyName: 
      type: string
      nullable: true
     VoidDate: 
      type: string
      format: date-time
      nullable: true
     Notes: 
      type: string
      nullable: true
     InvoiceRecordId: 
      type: integer
      nullable: true
     InvoiceNumber: 
      type: string
      nullable: true
     ReconciliationId: 
      type: integer
      nullable: true
     ReconciliationNumber: 
      type: string
      nullable: true
     LastUpdatedById: 
      type: integer
      nullable: true
     LastUpdatedBy: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
      nullable: true
     LineNumber: 
      type: integer
      nullable: true
     LineAmount: 
      type: number
      nullable: true
   PostClaimDTO: 
    title : PostClaimDTO
    type: object
    properties: 
     ClaimID: 
      type: integer
      nullable: true
     AdjustmentVersion: 
      type: integer
      nullable: true
     PostDate: 
      type: string
      format: date-time
      nullable: true
     Debug: 
      type: integer
      nullable: true
     CheckCriteria: 
      type: string
      nullable: true
     Raiserror: 
      type: integer
      nullable: true
   UpdatePostingRecordDTO: 
    title : UpdatePostingRecordDTO
    type: object
    properties: 
     RecordID: 
      type: integer
      nullable: true
     GracePeriodForRefund: 
      type: integer
      nullable: true
     PaymentClass: 
      type: string
      nullable: true
     MethodOfPayment: 
      type: string
      nullable: true
     Usage: 
      type: string
      nullable: true
   BillRecordsForClaimListDTO: 
    title : BillRecordsForClaimListDTO
    type: object
    properties: 
     RecordID: 
      type: integer
     ParentAccountID: 
      type: integer
     RecordTypeCode: 
      type: string
     RecordType: 
      type: string
      nullable: true
     RefundTypeCode: 
      type: string
      nullable: true
     RefundType: 
      type: string
      nullable: true
     MethodOfRefundCode: 
      type: string
      nullable: true
     MethodOfRefund: 
      type: string
      nullable: true
     MethodOfPaymentCode: 
      type: string
      nullable: true
     MethodOfPayment: 
      type: string
      nullable: true
     PaymentSubMethodCode: 
      type: string
      nullable: true
     PaymentSubMethod: 
      type: string
      nullable: true
     PaymentStatusCode: 
      type: string
      nullable: true
     PaymentStatus: 
      type: string
      nullable: true
     ExternalPaymentNumber: 
      type: string
      nullable: true
     ExternalPaymentDate: 
      type: string
      format: date-time
      nullable: true
     Amount: 
      type: number
     RemainingAmount: 
      type: number
      nullable: true
     TotalAmount: 
      type: number
      nullable: true
     PreviousBalance: 
      type: number
      nullable: true
     OpenAmount: 
      type: number
      nullable: true
     RecordStatusCode: 
      type: string
     RecordStatus: 
      type: string
      nullable: true
     EntityTypeCode: 
      type: string
      nullable: true
     ReferenceNumber: 
      type: integer
     JobId: 
      type: integer
      nullable: true
     JobNumber: 
      type: string
      nullable: true
     CreationDate: 
      type: string
      format: date-time
     ProcessedDate: 
      type: string
      format: date-time
     VoidDate: 
      type: string
      format: date-time
      nullable: true
     Notes: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
     LastUpdatedByID: 
      type: integer
     LastUpdatedBy: 
      type: string
      nullable: true
     BillId: 
      type: integer
      nullable: true
     BillNumber: 
      type: string
      nullable: true
     DateDue: 
      type: string
      format: date-time
      nullable: true
     DateDueForTermination: 
      type: string
      format: date-time
      nullable: true
     VoidReason: 
      type: string
      nullable: true
     UserReportId: 
      type: integer
      nullable: true
     UserReportName: 
      type: string
      nullable: true
     UserReportPath: 
      type: string
      nullable: true
     ExportType: 
      type: string
      nullable: true
     BillCSVReportId: 
      type: integer
      nullable: true
     BillCSVReportName: 
      type: string
      nullable: true
     BillCSVReportPath: 
      type: string
      nullable: true
     BillingEntityID: 
      type: integer
     BillingEntityName: 
      type: string
      nullable: true
     BillingEntityNumber: 
      type: string
      nullable: true
     BillTypeCode: 
      type: string
      nullable: true
     BillType: 
      type: string
      nullable: true
     PDFDocumentId: 
      type: integer
      nullable: true
     PDFFilePath: 
      type: string
      nullable: true
     PrintZeroDollarBill: 
      type: string
      nullable: true
     BillingEntityMapId: 
      type: integer
      nullable: true
     CashAccountName: 
      type: string
      nullable: true
     CompanyId: 
      type: integer
      nullable: true
     CompanyName: 
      type: string
      nullable: true
     CheckId: 
      type: integer
      nullable: true
     CheckNumber: 
      type: string
      nullable: true
     DepositNumber: 
      type: string
      nullable: true
     CheckTypeCode: 
      type: string
      nullable: true
     CheckType: 
      type: string
      nullable: true
     BillingEntityClass: 
      type: string
      nullable: true
     BillingEntitySubclass: 
      type: string
      nullable: true
     Class: 
      type: string
      nullable: true
     Subclass: 
      type: string
      nullable: true
     BillingEntityTypeCode: 
      type: string
      nullable: true
     BillingEntityType: 
      type: string
      nullable: true
     Message: 
      type: string
      nullable: true
  parameters: 
   ClaimIdQueryParam: 
    in: query
    name: ClaimId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   ClaimBillingRecordIdQueryParam: 
    in: query
    name: ClaimBillingRecordId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   UsageQueryParam: 
    in: query
    name: Usage
    required: false
    schema: 
     type: string
    description: description of parameter passed
   DebugFlagQueryParam: 
    in: query
    name: DebugFlag
    required: false
    schema: 
     type: integer
    description: description of parameter passed
