openapi: 3.0.0
info: 
  version: 1.0.0
  title: Group Claim API
  description: Groups Claim API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /Claims/getserviceareas/{GroupId}: 
   get: 
    operationId: GetServiceAreas
    tags: 
     - Group Claim
    summary: Get Service area
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/UsageQueryParam'
     - $ref: '#/components/parameters/GroupIdPathParam'
     - $ref: '#/components/parameters/DebugFlagQueryParam'
    responses: 
     '200': 
      description: Service areas retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/ServiceAreaListDTO'
  /Claims/updateservicearea: 
   put: 
    operationId: UpdateServiceArea
    tags: 
     - Group Claim
    summary: Update service area
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ServiceAreaDTO'
    responses: 
     '200': 
      description: Service area updated successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /Claims/addservicearea: 
   post: 
    operationId: AddServiceArea
    tags: 
     - Group Claim
    summary: Add Service area
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ServiceAreaDTO'
    responses: 
     '200': 
      description: Service area added successfully
      content: 
       application/json: 
        schema: 
         type: integer
  /Claims/deleteservicearea/{ServiceAreaId}: 
   delete: 
    operationId: DeleteServiceArea
    tags: 
     - Group Claim
    summary: Delete Service area
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/ServiceAreaIdPathParam'
     - $ref: '#/components/parameters/DebugFlagQueryParam'
    responses: 
     '200': 
      description: Service area deleted successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
  /Claims/getclaimfilingterm: 
   post: 
    operationId: GetClaimFilingTerm
    tags: 
     - Group Claim
    summary: Get claim filing term
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ClaimFilingTermSearchDTO'
    responses: 
     '200': 
      description: Claim filing term retrieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ClaimFilingTermListDTO'
  /Claims/getgroupbenefitpackage/{GroupId}: 
   get: 
    operationId: GetGroupBenefitPackage
    tags: 
     - Group Claim
    summary: Get group benefit package
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/GroupIdPathParam'
     - $ref: '#/components/parameters/AsOfDateQueryParam'
    responses: 
     '200': 
      description: Group benefit package retrieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/GroupBenefitPackageListDTO'
  /Claims/getgroupparents/{GroupId}: 
   get: 
    operationId: GetGroupParents
    tags: 
     - Group Claim
    summary: Get group parents
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/GroupIdPathParam'
     - $ref: '#/components/parameters/UsageQueryParam'
    responses: 
     '200': 
      description: Group parents retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/GroupParentsListDTO'
  /Claims/paymentpackageaggregatesummary: 
   post: 
    operationId: PaymentPackageAggregateSummary
    tags: 
     - Group Claim
    summary: Payment package aggregate summary
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/PaymentPackageAggregateSummarySearchDTO'
    responses: 
     '200': 
      description: Payment package aggregate summary retrieved successfully
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/PaymentPackageAggregateSummaryListDTO'
components: 
  schemas: 
   ClaimFilingTermListDTO: 
    title : ClaimFilingTermListDTO
    type: object
    properties: 
     ClaimFilingTermID: 
      type: integer
     EntityType: 
      type: string
     EntityId: 
      type: integer
     EntityName: 
      type: string
     EffectiveDate: 
      type: string
      format: date-time
     ExpirationDate: 
      type: string
      format: date-time
     FormType: 
      type: string
      nullable: true
     Form: 
      type: string
      nullable: true
     SourceType: 
      type: string
      nullable: true
     Source: 
      type: string
      nullable: true
     MemberFilingLimit: 
      type: integer
      nullable: true
     ProviderFilingLimit: 
      type: integer
      nullable: true
     ClaimFilingAction: 
      type: string
     ClaimFilingActionName: 
      type: string
      nullable: true
     FilingRulePrecedence: 
      type: string
     FilingRulePrecedenceName: 
      type: string
      nullable: true
     AsOfDate: 
      type: string
      format: date-time
      nullable: true
     LimitType: 
      type: string
     LimitTypeName: 
      type: string
      nullable: true
     FeeReductionType: 
      type: string
      nullable: true
     FeeReductionTypeName: 
      type: string
      nullable: true
     FeeReductionValue: 
      type: string
      nullable: true
     ExplanationID: 
      type: integer
      nullable: true
     ExplanationAbbreviation: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
     LastUpdatedBy: 
      type: string
   GroupBenefitPackageListDTO: 
    title : GroupBenefitPackageListDTO
    type: object
    properties: 
     BPBenefitCoverageId: 
      type: integer
      nullable: true
     BasePlanId: 
      type: integer
      nullable: true
     BasePlanCoverageType: 
      type: string
      nullable: true
     BasePlanName: 
      type: string
      nullable: true
     BasePlanPrintName: 
      type: string
      nullable: true
     CoverageEffectiveDate: 
      type: string
      format: date-time
      nullable: true
     CoverageExpirationDate: 
      type: string
      format: date-time
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      nullable: true
     TierTypeId: 
      type: integer
      nullable: true
     TierTypeCoverageType: 
      type: string
      nullable: true
     TierTypeName: 
      type: string
      nullable: true
     LiabilityPackageId: 
      type: integer
      nullable: true
     LiabilityPackageCoverageType: 
      type: string
      nullable: true
     LiabilityPackageName: 
      type: string
      nullable: true
     NetworkID: 
      type: integer
      nullable: true
     NetworkName: 
      type: string
      nullable: true
     UnfinishedJob: 
      type: string
      nullable: true
     LastUpdatedAt: 
      type: string
      format: date-time
      nullable: true
     LastUpdatedBy: 
      type: integer
      nullable: true
     LastUpdatedByName: 
      type: string
      nullable: true
   GroupParentsListDTO: 
    title : GroupParentsListDTO
    type: object
    properties: 
     RowID: 
      type: integer
     GroupId: 
      type: integer
     GroupName: 
      type: string
     ParentID: 
      type: integer
      nullable: true
     ChildCount: 
      type: integer
      nullable: true
   PaymentPackageAggregateSummarySearchDTO: 
    title : PaymentPackageAggregateSummarySearchDTO
    type: object
    properties: 
     JobId: 
      type: integer
      nullable: true
     PaymentPackageId: 
      type: integer
      nullable: true
     PackageEntityType: 
      type: string
      nullable: true
     PackageEntityId: 
      type: integer
      nullable: true
     GroupId: 
      type: integer
      nullable: true
     PostDate: 
      type: string
      nullable: true
     ShowGroupSummary: 
      type: string
      nullable: true
     ReturnResultsAsXml: 
      type: string
      nullable: true
     Usage: 
      type: string
      nullable: true
   PaymentPackageAggregateSummaryListDTO: 
    title : PaymentPackageAggregateSummaryListDTO
    type: object
    properties: 
     PostingDate: 
      type: string
      format: date-time
     ReinsurancePolicy: 
      type: string
     Group: 
      type: string
      nullable: true
     RecordId: 
      type: integer
      nullable: true
     MonthlyAttachmentPoint: 
      type: string
      nullable: true
     YTDAttachmentPoint: 
      type: string
      nullable: true
     ManuallyUpdated: 
      type: string
     Employee and Children: 
      type: string
      nullable: true
     Employee and Spouse: 
      type: string
      nullable: true
     Family: 
      type: string
      nullable: true
     Individual: 
      type: string
      nullable: true
  parameters: 
   UsageQueryParam: 
    in: query
    name: Usage
    required: true
    schema: 
     type: string
    description: description of parameter passed
   GroupIdPathParam: 
    in: path
    name: GroupId
    required: true
    schema: 
     type: integer
    description: description of parameter passed
   DebugFlagQueryParam: 
    in: query
    name: DebugFlag
    required: true
    schema: 
     type: integer
    description: description of parameter passed
   ServiceAreaIdPathParam: 
    in: path
    name: ServiceAreaId
    required: true
    schema: 
     type: integer
    description: description of parameter passed
   AsOfDateQueryParam: 
    in: query
    name: AsOfDate
    required: true
    schema: 
     type: string
     format: date-time
    description: description of parameter passed
