openapi: 3.0.0
info:
  version: 1.0.0
  title: Corporate Actions API V1
  description: Corporate Actions API V1
servers:
  - url: <to be set>
    description: API Server Description
security:
  - BasicAuth: []
paths:
  /corporateActions:
    get:
      operationId: getCorporateActions
      tags:
        - corporateActions
      summary: Get All Corporate Actions
      description: Get All Corporate Actions
      responses:
        '200':
          description: All Corporate Actions retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/corporateAction'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
    post:
      operationId: createCorporateActions
      tags:
        - corporateActions
      summary: Create Corporate Action
      description: Create Corporate Action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/corporateAction'
      responses:
        '200':
          description: Create Corporate Action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
  /corporateActions/{id}:
    get:
      operationId: getCorporateActionsById
      tags:
        - corporateActions
      summary: Get Corporate Action By Id
      description: Get Corporate Action By Id
      parameters:
        - $ref: '#/components/parameters/idPathParam'
      responses:
        '200':
          description: Corporate Action retrieved by Id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/corporateAction'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
    put:
      operationId: updateCorporateAction
      tags:
        - corporateActions
      summary: Update Corporate Action By Id
      description: Update Corporate Action By Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/corporateAction'
      parameters:
        - $ref: '#/components/parameters/idPathParam'
      responses:
        '200':
          description: Update Corporate Action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseList'
    delete:
      operationId: deleteCorporateAction
      tags:
        - corporateActions
      summary: Delete Corporate Action By Id
      description: Delete Corporate Action By Id
      parameters:
        - $ref: '#/components/parameters/idPathParam'
      responses:
        '200':
          description: Delete Corporate Action
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: oauth
  schemas:
    corporateAction:
      title: corporateAction
      type: object
      properties:
        id:
          type: number
          format: int64
          description: Corporate Actions Id
        corporateEventType:
          type: string
        corporateEventName:
          type: string
        corporateEventDate:
          type: string
          format: date
        tickerSymbol:
          type: string
        companyName:
          type: string
        announcementDate:
          type: string
          format: date
    ErrorResponseList:
      title: ErrorResponseList
      type: object
      properties:
        Error:
          type: object
          $ref: '#/components/schemas/Error'
    Error:
      title: Error
      type: object
      properties:
        ErrorCode:
          type: string
        ErrorDescription:
          type: string
    EntityResponse:
      title: EntityResponse
      type: object
      properties:
        status:
          type: string
        message:
          type: string
  parameters:
    idPathParam:
      in: path
      name: id
      required: true
      schema:
        type: string
      description: Id of Corporate Action to get details
