openapi: 3.0.0
info: 
  version: 1.0.0
  title: Corporate Actions API V1
  description: Corporate Actions API V1
servers: 
  - url: <to be set>
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
  /corporateActions: 
   post: 
    operationId: createCorporateActions
    tags: 
     - corporateActions
    summary: Create Corporate Action
    description: Create Corporate Action
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/corporateAction'
    responses: 
     '200': 
      description: Create Corporate Action
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/EntityResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
     '404': 
      description: Not Found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
   get: 
    operationId: getCorporateActions
    tags: 
     - corporateActions
    summary: Get All Corporate Actions
    description: Get All Corporate Actions
    responses: 
     '200': 
      description: All Corporate Actions retrieved
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/corporateAction'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
     '404': 
      description: Not Found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
  /corporateActions/{id}: 
   get: 
    operationId: getCorporateActionsById
    tags: 
     - corporateActions
    summary: Get Corporate Action By Id
    description: Get Corporate Action By Id
    parameters: 
     - $ref: '#/components/parameters/idPathParam'
    responses: 
     '200': 
      description: Corporate Action retrieved by Id
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/corporateAction'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
     '404': 
      description: Not Found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
   delete: 
    operationId: deleteCorporateAction
    tags: 
     - corporateActions
    summary: Delete Corporate Action By Id
    description: Delete Corporate Action By Id
    parameters: 
     - $ref: '#/components/parameters/idPathParam'
    responses: 
     '200': 
      description: Delete Corporate Action
      content: 
       application/json: 
        schema: 
         type: string
   put: 
    operationId: updateCorporateAction
    tags: 
     - corporateActions
    summary: Update Corporate Action By Id
    description: Update Corporate Action By Id
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/corporateAction'
    parameters: 
     - $ref: '#/components/parameters/idPathParam'
    responses: 
     '200': 
      description: Update Corporate Action
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/EntityResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
     '404': 
      description: Not Found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponseList'
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
  schemas: 
   ErrorResponseList: 
    title : ErrorResponseList
    type: object
    properties: 
     Error: 
      type: object
      $ref: '#/components/schemas/Error'
   EntityResponse: 
    title : EntityResponse
    type: object
    properties: 
     message: 
      type: string
     status: 
      type: string
   corporateAction: 
    title : corporateAction
    type: object
    properties: 
     corporateEventName: 
      type: string
     companyName: 
      type: string
     announcementDate: 
      type: string
      format: date
     tickerSymbol: 
      type: string
     id: 
      type: integer
      format: int64
     corporateEventType: 
      type: string
     corporateEventDate: 
      type: string
      format: date
   Error: 
    title : Error
    type: object
    properties: 
     ErrorDescription: 
      type: string
     ErrorCode: 
      type: string
  parameters: 
   idPathParam: 
    in: path
    name: id
    required: true
    schema: 
     type: string
     default: 
    description: Id of Corporate Action to get details
