openapi: 3.0.0
info: 
  version: 1.0.0
  title: Funds
  description: Funds API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /finance/funds/refundletters: 
   post: 
    operationId: CreateRefundLetters
    tags: 
     - Funds
    summary: Create Refund Letters
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/RefundLettersSearchDTO'
    responses: 
     '200': 
      description: RefundLetters Created successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/RefundLettersListDTO'
  /finance/funds/reinsurancerequestletters: 
   post: 
    operationId: CreateReinsuranceFundingRequestLetters
    tags: 
     - Funds
    summary: Create Reinsurance Funding Request Letters
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ReinsuranceFundingRequestLettersSearchDTO'
    responses: 
     '200': 
      description: ReInsuranceFundingRequest created successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/ReinsuranceFundingRequestLettersListDTO'
  /finance/funds/insufficientfundaccount: 
   get: 
    operationId: GetAccountsWithInsufficientFunds
    tags: 
     - Funds
    summary: Get Accounts With Insufficient Funds
    description: Description of path
    responses: 
     '200': 
      description: AccountsWithInsufficientFunds retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/AccountsWithInsufficientFundsListDTO'
  /finance/funds/transactions: 
   get: 
    operationId: GetTransactionsForFunding
    tags: 
     - Funds
    summary: Get Transaction For Funding
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/AccountIDQueryParam'
     - $ref: '#/components/parameters/DateQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
     - $ref: '#/components/parameters/DebugFlagQueryParam'
    responses: 
     '200': 
      description: TransactionsForFunding retrieved successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/TransactionsForFundingListDTO'
  /finance/funds/letters: 
   post: 
    operationId: CreateFundingLetters
    tags: 
     - Funds
    summary: Create Funding Letters
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/JobIDQueryParam'
    responses: 
     '200': 
      description: FundingLetters created successully
      content: 
       application/json: 
        schema: 
         type: integer
  /finance/funds/letterrecords: 
   get: 
    operationId: GetFundingLetterRecords
    tags: 
     - Funds
    summary: Get Funding Letter Records
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/JobIDQueryParam'
    responses: 
     '200': 
      description: FundingLetterRecords retrieved successully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/FundingLetterRecordsListDTO'
  /finance/funds/apply: 
   post: 
    operationId: ApplyFunds
    tags: 
     - Funds
    summary: Apply Funds
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/AccountIDQueryParam'
     - $ref: '#/components/parameters/FundedDateQueryParam'
     - $ref: '#/components/parameters/FundedNotesQueryParam'
     - $ref: '#/components/parameters/FundedAmountQueryParam'
    responses: 
     '200': 
      description: Funds applied successully
      content: 
       application/json: 
        schema: 
         type: integer
  /finance/funds/availability: 
   null: 
    operationId: CheckFundsAvailability
    tags: 
     - Funds
    summary: Check Funds Availability
    description: Description of path
