openapi: 3.0.0
info: 
  version: 1.0.0
  title: ts-mdm-sys
  description: MDM System API
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /Export: 
   post: 
    operationId: post_Export_1
    tags: 
     - Export
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_1_req'
    parameters: 
     - $ref: '#/components/parameters/entityTypeQueryParam'
     - $ref: '#/components/parameters/messageidHeaderParam'
     - $ref: '#/components/parameters/tenantIdHeaderParam'
     - $ref: '#/components/parameters/jobIdHeaderParam'
     - $ref: '#/components/parameters/transactionIdHeaderParam'
     - $ref: '#/components/parameters/targetCodeHeaderParam'
     - $ref: '#/components/parameters/sourceCodeHeaderParam'
     - $ref: '#/components/parameters/sourceNameHeaderParam'
     - $ref: '#/components/parameters/entityDomainCodeHeaderParam'
     - $ref: '#/components/parameters/entityTypeHeaderParam'
     - $ref: '#/components/parameters/idlFlagHeaderParam'
     - $ref: '#/components/parameters/countryCodeHeaderParam'
     - $ref: '#/components/parameters/dcrStatusFlagHeaderParam'
    responses: 
     '200': 
      description: post_Export_1
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_1_200_res'
     '400': 
      description: A request was malformed
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_1_400_res'
     '404': 
      description: resource not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_1_404_res'
     '500': 
      description: internal server error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_1_500_res'
  /Export/{TaskId}: 
   post: 
    operationId: post_Export_TaskId_2
    tags: 
     - Export
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_TaskId_2_req'
    parameters: 
     - $ref: '#/components/parameters/TaskIdPathParam'
     - $ref: '#/components/parameters/messageidHeaderParam'
     - $ref: '#/components/parameters/tenantIdHeaderParam'
     - $ref: '#/components/parameters/jobIdHeaderParam'
     - $ref: '#/components/parameters/transactionIdHeaderParam'
     - $ref: '#/components/parameters/targetCodeHeaderParam'
     - $ref: '#/components/parameters/sourceCodeHeaderParam'
     - $ref: '#/components/parameters/sourceNameHeaderParam'
     - $ref: '#/components/parameters/entityDomainCodeHeaderParam'
     - $ref: '#/components/parameters/entityTypeHeaderParam'
     - $ref: '#/components/parameters/idlFlagHeaderParam'
     - $ref: '#/components/parameters/countryCodeHeaderParam'
     - $ref: '#/components/parameters/dcrStatusFlagHeaderParam'
    responses: 
     '200': 
      description: post_Export_TaskId_2
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_TaskId_2_200_res'
     '400': 
      description: A request was malformed
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_TaskId_2_400_res'
     '500': 
      description: Server-side issue
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Export_TaskId_2_500_res'
  /Merge: 
   post: 
    operationId: post_Merge_3
    tags: 
     - Merge
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Merge_3_req'
    parameters: 
     - $ref: '#/components/parameters/messageidHeaderParam'
     - $ref: '#/components/parameters/tenantIdHeaderParam'
     - $ref: '#/components/parameters/jobIdHeaderParam'
     - $ref: '#/components/parameters/transactionIdHeaderParam'
     - $ref: '#/components/parameters/targetCodeHeaderParam'
     - $ref: '#/components/parameters/sourceCodeHeaderParam'
     - $ref: '#/components/parameters/sourceNameHeaderParam'
     - $ref: '#/components/parameters/entityDomainCodeHeaderParam'
     - $ref: '#/components/parameters/entityTypeHeaderParam'
     - $ref: '#/components/parameters/idlFlagHeaderParam'
     - $ref: '#/components/parameters/countryCodeHeaderParam'
     - $ref: '#/components/parameters/dcrStatusFlagHeaderParam'
    responses: 
     '200': 
      description: post_Merge_3
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Merge_3_200_res'
     '400': 
      description: A request was malformed
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Merge_3_400_res'
     '404': 
      description: resource not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Merge_3_404_res'
     '500': 
      description: internal server error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_Merge_3_500_res'
  /DCRStatus/{DCRUri}: 
   post: 
    operationId: post_DCRStatus_DCRUri_4
    tags: 
     - DCRStatus
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_DCRStatus_DCRUri_4_req'
    parameters: 
     - $ref: '#/components/parameters/DCRUriPathParam'
     - $ref: '#/components/parameters/DCROperationTypeQueryParam'
     - $ref: '#/components/parameters/messageidHeaderParam'
     - $ref: '#/components/parameters/tenantIdHeaderParam'
     - $ref: '#/components/parameters/jobIdHeaderParam'
     - $ref: '#/components/parameters/transactionIdHeaderParam'
     - $ref: '#/components/parameters/targetCodeHeaderParam'
     - $ref: '#/components/parameters/sourceCodeHeaderParam'
     - $ref: '#/components/parameters/sourceNameHeaderParam'
     - $ref: '#/components/parameters/entityDomainCodeHeaderParam'
     - $ref: '#/components/parameters/entityTypeHeaderParam'
     - $ref: '#/components/parameters/idlFlagHeaderParam'
     - $ref: '#/components/parameters/countryCodeHeaderParam'
     - $ref: '#/components/parameters/dcrStatusFlagHeaderParam'
     - $ref: '#/components/parameters/crosswalkIdHeaderParam'
    responses: 
     '200': 
      description: post_DCRStatus_DCRUri_4
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_DCRStatus_DCRUri_4_200_res'
     '400': 
      description: A request was malformed
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_DCRStatus_DCRUri_4_400_res'
     '500': 
      description: Server-side issue
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/post_DCRStatus_DCRUri_4_500_res'
  /CheckCertificationExpiry: 
   get: 
    operationId: get_CheckCertificationExpiry_5
    tags: 
     - CheckCertificationExpiry
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/messageidHeaderParam'
    responses: 
     '200': 
      description: get_CheckCertificationExpiry_5
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/get_CheckCertificationExpiry_5_200_res'
     '400': 
      description: A request was malformed
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/get_CheckCertificationExpiry_5_400_res'
     '500': 
      description: Server issue
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/get_CheckCertificationExpiry_5_500_res'
components: 
  schemas: 
   post_Export_1_200_res: 
    title : post_Export_1_200_res
    type: object
    properties: 
     groupId: 
      type: string
     exportType: 
      type: string
     version: 
      type: string
     status: 
      type: string
     details: 
      type: string
     taskIds: 
      type: array
      items: 
       type: string
   post_Export_1_400_res: 
    title : post_Export_1_400_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   error: 
    title : error
    type: object
    properties: 
     code: 
      type: integer
     message: 
      type: string
     errors: 
      type: array
      items: 
       $ref: '#/components/schemas/errorerrorsArray'
   errorerrorsArray: 
    title : errorerrorsArray
    type: object
    properties: 
     domain: 
      type: string
     reason: 
      type: string
     message: 
      type: string
     location: 
      type: string
     locationType: 
      type: string
     extendedHelp: 
      type: string
     transactionId: 
      type: string
   post_Export_1_404_res: 
    title : post_Export_1_404_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Export_1_500_res: 
    title : post_Export_1_500_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   s3BucketDetails: 
    title : s3BucketDetails
    type: object
    properties: 
     s3Path: 
      type: string
   post_Export_1_req: 
    title : post_Export_1_req
    type: object
    properties: 
     s3BucketDetails: 
      type: object
      $ref: '#/components/schemas/s3BucketDetails'
     ExportDetails: 
      type: object
      $ref: '#/components/schemas/ExportDetails'
     Config: 
      type: object
      $ref: '#/components/schemas/Config'
   ExportDetails: 
    title : ExportDetails
    type: object
    properties: 
     ovOnly: 
      type: boolean
     updateTimeFilter: 
      type: object
      $ref: '#/components/schemas/updateTimeFilter'
   updateTimeFilter: 
    title : updateTimeFilter
    type: object
    properties: 
     since: 
      type: string
     to: 
      type: string
   Config: 
    title : Config
    type: object
    properties: 
     credentials: 
      type: string
   post_Export_TaskId_2_200_res: 
    title : post_Export_TaskId_2_200_res
    type: object
    properties: 
     id: 
      type: string
     groupId: 
      type: string
     createdBy: 
      type: string
     updatedBy: 
      type: string
     type: 
      type: string
     status: 
      type: string
     name: 
      type: string
     createdOnHost: 
      type: string
     executedOnHost: 
      type: string
     parallelExecution: 
      type: boolean
     nodesGroup: 
      type: string
     parameters: 
      type: object
      $ref: '#/components/schemas/parameters'
     currentState: 
      type: object
      $ref: '#/components/schemas/currentState'
     throughput: 
      type: number
     duration: 
      type: string
   parameters: 
    title : parameters
    type: object
    properties: 
     updatedSince: 
      type: string
     distributedTaskIndex: 
      type: string
     s3Path: 
      type: string
     partSize: 
      type: string
     headersStyle: 
      type: string
     specifiedMailAddress: 
      type: string
     taskId: 
      type: string
     useEsHeadersCollectionExport: 
      type: string
     updatedBefore: 
      type: string
     activeness: 
      type: string
     fileFormat: 
      type: string
     parallelTasksIds: 
      type: string
     tenantId: 
      type: string
     skipPostprocessing: 
      type: string
     s3Bucket: 
      type: string
     includeType: 
      type: string
     queryParams: 
      type: string
     exportName: 
      type: string
     userRoles: 
      type: string
     ovOnly: 
      type: string
     username: 
      type: string
     encryptUrl: 
      type: string
     headerFormat: 
      type: string
     sePrefix: 
      type: string
     distributedTasksPartsCount: 
      type: string
     dateFormat: 
      type: string
     mailAddress: 
      type: string
     exportPath: 
      type: string
   currentState: 
    title : currentState
    type: object
    properties: 
     statusId: 
      type: number
     status: 
      type: string
     lastExecutionEC2Instances: 
      type: string
     lastHourThroughput: 
      type: number
     numberOfProcessedObjects: 
      type: number
     numberOfFailedToPublishEvents: 
      type: number
     numberOfObjects: 
      type: number
     globalStatus: 
      type: object
      $ref: '#/components/schemas/globalStatus'
     exportUrls: 
      type: array
      items: 
       type: string
   globalStatus: 
    title : globalStatus
    type: object
    properties: 
     lastFiveMinReadThroughput: 
      type: number
     lastFiveMinThroughput: 
      type: number
     entitiesTotal: 
      type: number
     entitiesNumber: 
      type: number
     overallThroughput: 
      type: number
     overallReadThroughput: 
      type: number
   currentStateexportUrlsArray: 
    title : currentStateexportUrlsArray
    type: object
    properties: 
     exportUrls: 
      type: string
   post_Export_TaskId_2_400_res: 
    title : post_Export_TaskId_2_400_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Export_TaskId_2_500_res: 
    title : post_Export_TaskId_2_500_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Export_TaskId_2_req: 
    title : post_Export_TaskId_2_req
    type: object
    properties: 
     Config: 
      type: object
      $ref: '#/components/schemas/Config'
   post_Merge_3_200_res: 
    title : post_Merge_3_200_res
    type: object
    properties: 
     groupId: 
      type: string
     exportType: 
      type: string
     version: 
      type: string
     status: 
      type: string
     details: 
      type: string
     taskIds: 
      type: array
      items: 
       type: string
   post_Merge_3_400_res: 
    title : post_Merge_3_400_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Merge_3_404_res: 
    title : post_Merge_3_404_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Merge_3_500_res: 
    title : post_Merge_3_500_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_Merge_3_req: 
    title : post_Merge_3_req
    type: object
    properties: 
     s3BucketDetails: 
      type: object
      $ref: '#/components/schemas/s3BucketDetails'
     ExportDetails: 
      type: object
      $ref: '#/components/schemas/ExportDetails'
     Config: 
      type: object
      $ref: '#/components/schemas/Config'
   post_DCRStatus_DCRUri_4_200_res: 
    title : post_DCRStatus_DCRUri_4_200_res
    type: object
    properties: 
     entityUri: 
      type: string
     entityType: 
      type: string
     hasAddressUri: 
      type: string
     activityUri: 
      type: string
     dcrStatus: 
      type: string
     dcrMessage: 
      type: object
   post_DCRStatus_DCRUri_4_400_res: 
    title : post_DCRStatus_DCRUri_4_400_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_DCRStatus_DCRUri_4_500_res: 
    title : post_DCRStatus_DCRUri_4_500_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   post_DCRStatus_DCRUri_4_req: 
    title : post_DCRStatus_DCRUri_4_req
    type: object
    properties: 
     Config: 
      type: object
      $ref: '#/components/schemas/Config'
     sourceEntityIds: 
      type: array
      items: 
       type: string
   get_CheckCertificationExpiry_5_200_res: 
    title : get_CheckCertificationExpiry_5_200_res
    type: object
    properties: 
     CreatedDate: 
      type: string
     CurrentDate: 
      type: string
     ExpirationDate: 
      type: string
     ExpiringInDays: 
      type: integer
     FeatureName: 
      type: string
     LicenseOwner: 
      type: string
     ValidVersion: 
      type: string
     VendorName: 
      type: string
   get_CheckCertificationExpiry_5_400_res: 
    title : get_CheckCertificationExpiry_5_400_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
   get_CheckCertificationExpiry_5_500_res: 
    title : get_CheckCertificationExpiry_5_500_res
    type: object
    properties: 
     apiVersion: 
      type: string
     error: 
      type: object
      $ref: '#/components/schemas/error'
  parameters: 
   entityTypeQueryParam: 
    in: query
    name: entityType
    required: true
    schema: 
     type: string
    description: Entity Type
   messageidHeaderParam: 
    in: header
    name: messageid
    required: false
    schema: 
     type: string
    description: A messageid uniquely identifies a message coming Anypoint MQ. Having a messageid allows us to fully reconstruct how a particular value ended-up in our dbs, using Splunk or similar system.
   tenantIdHeaderParam: 
    in: header
    name: tenantId
    required: true
    schema: 
     type: string
    description: Tenant Identifier (guid)
   jobIdHeaderParam: 
    in: header
    name: jobId
    required: true
    schema: 
     type: string
    description: job id
   transactionIdHeaderParam: 
    in: header
    name: transactionId
    required: true
    schema: 
     type: string
    description: transaction id
   targetCodeHeaderParam: 
    in: header
    name: targetCode
    required: false
    schema: 
     type: string
     format: array
    description: application targetCode
   sourceCodeHeaderParam: 
    in: header
    name: sourceCode
    required: false
    schema: 
     type: string
    description: application sourceCode
   sourceNameHeaderParam: 
    in: header
    name: sourceName
    required: false
    schema: 
     type: string
    description: sourceName for country
   entityDomainCodeHeaderParam: 
    in: header
    name: entityDomainCode
    required: false
    schema: 
     type: string
    description: application entityDomainCode
   entityTypeHeaderParam: 
    in: header
    name: entityType
    required: false
    schema: 
     type: string
    description: entityType
   idlFlagHeaderParam: 
    in: header
    name: idlFlag
    required: false
    schema: 
     type: number
    description: IDL Flag
   countryCodeHeaderParam: 
    in: header
    name: countryCode
    required: false
    schema: 
     type: string
    description: countryCode
   dcrStatusFlagHeaderParam: 
    in: header
    name: dcrStatusFlag
    required: false
    schema: 
     type: number
    description: DCR Status Flag
   TaskIdPathParam: 
    in: path
    name: TaskId
    required: true
    schema: 
     type: string
    description: description of parameter passed
   DCRUriPathParam: 
    in: path
    name: DCRUri
    required: true
    schema: 
     type: string
    description: description of parameter passed
   DCROperationTypeQueryParam: 
    in: query
    name: DCROperationType
    required: true
    schema: 
     type: string
    description: description of parameter passed
   crosswalkIdHeaderParam: 
    in: header
    name: crosswalkId
    required: false
    schema: 
     type: string
    description: description of parameter passed
