openapi: 3.0.0
info: 
  version: 1.0.0
  title: ItemsAPI
  description: Items API
servers: 
  - url: https://test.com
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
  /items: 
   get: 
    operationId: listItems
    tags: 
     - items
    summary: Get All Items
    description: Get All Items
    responses: 
     '200': 
      description: Items Retrieved
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/Items'
  /items/{id}: 
   get: 
    operationId: listItemById
    tags: 
     - item
    summary: Get Item By Id
    description: Get Item By Id
    parameters: 
     - $ref: '#/components/parameters/idPathParam'
    responses: 
     '200': 
      description: Item retrieved by Id
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/Items'
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
  schemas: 
   Items: 
    title : Items
    type: object
    properties: 
     itemId: 
      type: string
     itemName: 
      type: string
     ItemDetails: 
      type: object
      $ref: '#/components/schemas/ItemDetails'
     Cover: 
      type: object
      $ref: '#/components/schemas/Cover'
     PersonUser: 
      type: object
      $ref: '#/components/schemas/PersonUser'
     Purchase: 
      type: object
      $ref: '#/components/schemas/Purchase'
   ItemDetails: 
    title : ItemDetails
    type: object
    properties: 
     ItemCode: 
      type: string
     ItemCodeDescription: 
      type: string
     ManufacturerBrandCode: 
      type: string
     ManufacturerBrandDescription: 
      type: string
     GoodsColour: 
      type: string
     ModelNumber: 
      type: string
     SerialNumber: 
      type: string
     OperationalStatusCode: 
      type: string
     AllocatedSupplierAgentCode: 
      type: string
     AllocatedSupplierBranchCode: 
      type: string
     LastServiceDate: 
      type: string
     LastServiceTime: 
      type: string
     ItemCatCode: 
      type: string
     ManufacturerBrandGroupCode: 
      type: string
   Cover: 
    title : Cover
    type: object
    properties: 
     ManufacturerGuaranteeLabourMonths: 
      type: integer
     ManufacturerGuaranteePartsMonths: 
      type: integer
     ThirdPartyGuaranteeLabourMonths: 
      type: integer
     ThirdPartyGuaranteePartsMonths: 
      type: integer
   PersonUser: 
    title : PersonUser
    type: object
    properties: 
     PreviousClientURN: 
      type: string
     ClientURN: 
      type: string
     PreviousEID: 
      type: string
     EID: 
      type: string
     SrcCode: 
      type: string
   Purchase: 
    title : Purchase
    type: object
    properties: 
     PriceCurrencyCode: 
      type: string
     PurchaseDate: 
      type: string
     PurchaseTime: 
      type: string
     RecommendedPriceCurrencyCode: 
      type: string
     PurchaseRetailer: 
      type: string
     PurchasePrice: 
      type: integer
     RecommendedPrice: 
      type: integer
  parameters: 
   idPathParam: 
    in: path
    name: id
    required: true
    schema: 
     type: string
     default: 1
    description: Item Id
