openapi: 3.0.0
info: 
  version: 1.0.0
  title: CustomerAPI
  description: Customer API
servers: 
  - url: 
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
  /customers: 
   get: 
    operationId: listcustomers
    tags: 
     - customer
    description: Get Customers
    parameters: 
     - $ref: '#/components/parameters/idParam'
    responses: 
     '200': 
      description: List of customers retrieved
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/customer'
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
  schemas: 
   customer: 
    title : customer
    type: object
    properties: 
     id: 
      type: string
     firstName: 
      type: string
     lastName: 
      type: string
     email: 
      type: string
  parameters: 
   idParam: 
    in: query
    name: id
    required: true
    schema: 
     type: string
    description: Customer Id
