openapi: 3.0.0
info:
  title: Claims API
  description: API for accessing and managing claims information
  version: 1.0.0
servers:
  - url: https://api.example.com/v1

paths:
  /claims:
    get:
      operationId: getAllClaims
      summary: Get all claims
      responses:
        '200':
          description: A list of claims
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
                  type: object
    post:
      operationId: createClaim
      summary: Create a new claim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
              type: object
      responses:
        '201':
          description: Claim created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
                type: object

  /claims/{claimId}:
    get:
      operationId: getClaimById
      summary: Get claim by ID
      parameters:
        - $ref: '#/components/parameters/ClaimId'
          type: string
      responses:
        '200':
          description: A single claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
                type: object
    
    delete:
      operationId: deleteClaimById
      summary: Delete claim by ID
      parameters:
        - $ref: '#/components/parameters/ClaimId'
          type: string
      responses:
        '204':
          description: Claim deleted successfully
    
    patch:
      operationId: updateClaimById
      summary: Update claim by ID
      parameters:
        - $ref: '#/components/parameters/ClaimId'
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                adjudication:
                  $ref: '#/components/schemas/Adjudication'
                  type: object
      responses:
        '200':
          description: Claim updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
                type: object

components:
  parameters:
    ClaimId:
      name: claimId
      in: path
      required: true
      schema:
        type: string

  schemas:
    Claim:
      type: object
      properties:
        claimId:
          type: string
        dateOfService:
          type: string
          format: date
        status:
          type: string
        patient:
          $ref: '#/components/schemas/Patient'
          type: object
        prescriber:
          $ref: '#/components/schemas/Prescriber'
          type: object
        pharmacy:
          $ref: '#/components/schemas/Pharmacy'
          type: object
        medication:
          $ref: '#/components/schemas/Medication'
          type: object
        pricing:
          $ref: '#/components/schemas/Pricing'
          type: object
        adjudication:
          $ref: '#/components/schemas/Adjudication'
          type: object
        utilizationManagement:
          $ref: '#/components/schemas/UtilizationManagement'
          type: object
    
    Patient:
      type: object
      properties:
        patientId:
          type: string
        name:
          type: string
        dateOfBirth:
          type: string
          format: date
        gender:
          type: string
        insurance:
          $ref: '#/components/schemas/Insurance'
          type: object
    
    Insurance:
      type: object
      properties:
        planId:
          type: string
        policyNumber:
          type: string
        coverageStartDate:
          type: string
          format: date
        coverageEndDate:
          type: string
          format: date
          nullable: true
    
    Prescriber:
      type: object
      properties:
        prescriberId:
          type: string
        name:
          type: string
        npi:
          type: string
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
          type: object
    
    Pharmacy:
      type: object
      properties:
        pharmacyId:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
          type: object
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
          type: object
    
    Address:
      type: object
      properties:
        line1:
          type: string
        line2:
          type: string
          nullable: true
        city:
          type: string
        state:
          type: string
        zip:
          type: string
    
    ContactInformation:
      type: object
      properties:
        phone:
          type: string
        fax:
          type: string
        email:
          type: string
    
    Medication:
      type: object
      properties:
        drugCode:
          type: string
        drugName:
          type: string
        strength:
          type: string
        quantity:
          type: integer
        daysSupply:
          type: integer
        dosageForm:
          type: string
        routeOfAdministration:
          type: string
    
    Pricing:
      type: object
      properties:
        totalCost:
          type: number
          format: float
        insurancePaid:
          type: number
          format: float
        patientPaid:
          type: number
          format: float
        rebate:
          type: number
          format: float
    
    Adjudication:
      type: object
      properties:
        adjudicationDate:
          type: string
          format: date
        adjudicatedBy:
          type: string
        notes:
          type: string
    
    UtilizationManagement:
      type: object
      properties:
        priorAuthorizationRequired:
          type: boolean
        stepTherapyRequired:
          type: boolean
        quantityLimit:
          type: integer
