openapi: 3.0.0
info: 
  version: 1.0.0
  title: Provider Credential
  description: Provider Credential
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /provider/credentials: 
   post: 
    operationId: GetProviderCredentials
    tags: 
     - Provider Credential
    summary: Get Provider Credential
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/ProviderIdQueryParam'
     - $ref: '#/components/parameters/ProviderCredentialIDQueryParam'
     - $ref: '#/components/parameters/UsageQueryParam'
     - $ref: '#/components/parameters/CredentialTypeQueryParam'
     - $ref: '#/components/parameters/FlagQueryParam'
    responses: 
     '200': 
      description: Provider Credentials Retreived Successfully
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          $ref: '#/components/schemas/ProviderCredentialListDTO'
  /provider/credential: 
   post: 
    operationId: AddProviderCredential
    tags: 
     - Provider Credential
    summary: Add Provider Credential
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ProviderCredentialDTO'
    responses: 
     '200': 
      description: Provider Credential Added Successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
   put: 
    operationId: UpdateProviderCredential
    tags: 
     - Provider Credential
    summary: Update Provider Credential
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ProviderCredentialDTO'
    responses: 
     '200': 
      description: Provider Credential Updated Successfully
      content: 
       application/json: 
        schema: 
         type: integer
   delete: 
    operationId: DeleteProviderCredential
    tags: 
     - Provider Credential
    summary: Delete Provider Credential
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/ProviderCredentialIDQueryParam'
    responses: 
     '200': 
      description: Provider Credential deleted Successfully
      content: 
       application/json: 
        schema: 
         type: integer
         nullable: true
components: 
  schemas: 
   ProviderCredentialListDTO: 
    title : ProviderCredentialListDTO
    type: object
    properties: 
     ProviderCredentialID: 
      type: integer
     ProviderID: 
      type: integer
      description: 
     CredentialType: 
      type: string
     CredTypeName: 
      type: string
      nullable: true
     CredentialSubType: 
      type: string
     CredentialEntity: 
      type: string
     CredSubTypeName: 
      type: string
      nullable: true
     CredentialNumber: 
      type: string
      nullable: true
     SpecialtyId: 
      type: integer
      nullable: true
     SpecialtyName: 
      type: string
      nullable: true
     CredentialDate: 
      type: string
      format: date-time
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      nullable: true
     State: 
      type: string
      nullable: true
     VerificationSource: 
      type: string
      nullable: true
     VerificationContact: 
      type: string
      nullable: true
     VerifiedDate: 
      type: string
      format: date-time
      nullable: true
     VerifiedBy: 
      type: integer
      nullable: true
     ReverificationDate: 
      type: string
      format: date-time
      nullable: true
     ReferenceNumber: 
      type: string
      nullable: true
     DocumentID: 
      type: integer
      nullable: true
     Comments: 
      type: string
      nullable: true
     LastupdatedBy: 
      type: string
      nullable: true
     LastupdatedAt: 
      type: string
      format: date-time
     Amount: 
      type: number
      nullable: true
     TotalAmount: 
      type: number
      nullable: true
     FacilityID: 
      type: integer
      nullable: true
     FacilityName: 
      type: string
      nullable: true
     ProviderName: 
      type: string
      nullable: true
   ProviderCredentialDTO: 
    title : ProviderCredentialDTO
    type: object
    properties: 
     ProviderID: 
      type: integer
      nullable: true
     CredentialType: 
      type: string
      nullable: true
     CredentialSubType: 
      type: string
      nullable: true
     CredentialEntity: 
      type: string
      nullable: true
     CredentialNumber: 
      type: string
      nullable: true
     SpecialtyId: 
      type: integer
      nullable: true
     CredentialDate: 
      type: string
      format: date-time
      nullable: true
     EffectiveDate: 
      type: string
      format: date-time
      nullable: true
     ExpirationDate: 
      type: string
      format: date-time
      nullable: true
     State: 
      type: string
      nullable: true
     VerificationSource: 
      type: string
      nullable: true
     VerificationContact: 
      type: string
      nullable: true
     VerifiedDate: 
      type: string
      format: date-time
      nullable: true
     VerifiedBy: 
      type: integer
      nullable: true
     ReverificationDate: 
      type: string
      format: date-time
      nullable: true
     ReferenceNumber: 
      type: string
      nullable: true
     DocumentID: 
      type: integer
      nullable: true
     Comments: 
      type: string
      nullable: true
     Amount: 
      type: number
      nullable: true
     TotalAmount: 
      type: number
      nullable: true
     FacilityID: 
      type: integer
      nullable: true
     ProviderCredentialID: 
      type: integer
      nullable: true
     UpdateUsage: 
      type: string
      nullable: true
  parameters: 
   ProviderIdQueryParam: 
    in: query
    name: ProviderId
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   ProviderCredentialIDQueryParam: 
    in: query
    name: ProviderCredentialID
    required: false
    schema: 
     type: integer
    description: description of parameter passed
   UsageQueryParam: 
    in: query
    name: Usage
    required: false
    schema: 
     type: string
    description: description of parameter passed
   CredentialTypeQueryParam: 
    in: query
    name: CredentialType
    required: false
    schema: 
     type: string
    description: description of parameter passed
   FlagQueryParam: 
    in: query
    name: Flag
    required: false
    schema: 
     type: integer
    description: description of parameter passed
