swagger: "2.0"
info: 
  title: Alternate_Address API
  description: Alternate_Address API V1
  version: 1.0.1
host: www.apiexample.com
basePath: /v1
schemes: 
  - http
paths: 
  /AlternateAddress/addalternateaddress: 
   post: 
    tags: 
     - AlternateAddress
    description: Description of path
    produces: 
     - application/json
     - application/xml
    parameters: 
     - name: AlternateAddressDTO
       in: body
       description: 
       required: true
       schema: 
        $ref: '#/definitions/AlternateAddressDTO'
    responses: 
     '200': 
      description: Success
  /AlternateAddress/updatealternateaddress: 
   put: 
    tags: 
     - AlternateAddress
    description: Description of path
    produces: 
     - application/json
     - application/xml
    parameters: 
     - name: AlternateAddressDTO
       in: body
       description: 
       required: true
       schema: 
        $ref: '#/definitions/AlternateAddressDTO'
    responses: 
     '200': 
      description: Success
  /AlternateAddress/deletealternateaddress/{AlternateAddressID}: 
   delete: 
    tags: 
     - AlternateAddress
    description: Description of path
    produces: 
     - application/json
     - application/xml
    parameters: 
     - $ref: '#/parameters/AlternateAddressIDParam'
    responses: 
     '200': 
      description: Success
definitions: 
   AlternateAddressHistoryListDTO: 
    type: object
    properties: 
     Zip: 
      type: string
     HistoryID: 
      type: integer
     LastUpdatedAt: 
      type: string
     LONGITUDE: 
      type: float
     ChangedAt: 
      type: string
     ZipSearch: 
      type: string
     County: 
      type: string
     ZipCodeId: 
      type: integer
     Name: 
      type: string
     EntityID: 
      type: integer
     AlternateAddressTypeCode: 
      type: string
     ChangeType: 
      type: string
     Phone: 
      type: string
     LastUpdatedByName: 
      type: string
     CountryCode: 
      type: string
     ChangedByName: 
      type: string
     LastUpdatedBy: 
      type: integer
     SpecialInstructions: 
      type: string
     ChangedBy: 
      type: integer
     Address2: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     EntityType: 
      type: string
     AlternateAddressType: 
      type: string
     ExpirationDate: 
      type: string
     State: 
      type: string
     CountryISOCode2: 
      type: string
     CountryISOCode3: 
      type: string
     LATITUDE: 
      type: float
     AlternateAddressID: 
      type: integer
     EffectiveDate: 
      type: string
   AlternateAddressReturnDTO: 
    type: object
    properties: 
     LastUpdatedAt: 
      type: string
     LastUpdatedBy: 
      type: string
     AlternateAddressID: 
      type: integer
parameters: 
   AlternateAddressIDParam: 
    in: path
    name: AlternateAddressID
    type: integer
    required: true
    description: description of parameter passed
