openapi: 3.0.0
info: 
  version: 1.0.0
  title: Test
  description: Test
servers: 
  - url: 
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
  /test: 
   get: 
    operationId: Test
    tags: 
     - tag
    summary: sum
    description: desc
    parameters: 
     - $ref: '#/components/parameters/TestHeaderHeaderParam'
    responses: 
     '200': 
      description: desc
      content: 
       application/json: 
        schema: 
         type: array
         items: 
          type: string
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
  parameters: 
   TestHeaderHeaderParam: 
    in: header
    name: TestHeader
    required: false
    schema: 
     type: string
     default: 
    description: desc
