openapi: 3.0.0
info: 
  version: 1.0.0
  title: API Title
  description: API description
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /member: 
   get: 
    operationId: lOQkpR6p
    tags: 
     - member
    description: Description of path
    responses: 
     '200': 
      description: Success
  /member/SetGoGreenSubscription: 
   post: 
    operationId: QnwgCjMr
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/client_secretParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
  /member/letters/{nameId}: 
   get: 
    operationId: miTxqAdn
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/nameIdParam'
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/client_secretParam'
    responses: 
     '200': 
      description: Success
  /member/pbpChange: 
   post: 
    operationId: DEErjr28
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/client_secretParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
components: 
  schemas: 
   QnwgCjMr: 
    type: object
    properties: 
     QnwgCjMr: 
      type: object
      $ref: '#/components/schemas/QnwgCjMr'
   DEErjr28: 
    type: object
    properties: 
     DEErjr28: 
      type: object
      $ref: '#/components/schemas/DEErjr28'
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   nameIdParam: 
    in: path
    name: nameId
    required: true
    schema: 
     type: string
    description: nameId
